appUrl=https://www.automationexercise.com/#google_vignette
email=gFDKD3308@gmail.com
pass=tZlne@829

email2=lRJk@gmail.com
pass2=AzyWy@17

//Contact us page
name=Yogesh11
email3=vgvjl145b3u@gmail.com
subject=Complaint
message=pelase provide better service